### ISSUE TITLE
Lazy translation strings are rendered as arrays

### ISSUE THREAD

**Issue by jamesjwarren** [jozo/djangorestframework-camel-case2#13]
When lazy translation strings go through the camel case renderer as values they are rendered as arrays instead of strings.

```py
from django.utils.translation import gettext_lazy as _
```
**Expected**
`{ 'someKey': _('Example') }` => `{ "someKey": "Example" }`
Expected the lazy translation string to be rendered as a string.

**Actual**
`{ 'someKey': _('Example') }` => `{ "someKey": ["E", "x", "a", "m", "p", "l", "e"]}`
It was actually rendered as an array.

--- 

It seems this is to do with how `util.py(17)camelize` determines whether a value is a string or an iterable. The output from `gettext_lazy` is not an instance of `str` and passes the `is_iterable` check, so it falls through the `if is_iterable(data) and not isinstance(data, six.string_types):` check and is iterated over producing the above output.

**Comment by jozo** [comment]
@jamesjwarren I released new version with your fix

**Comment by jamesjwarren** [comment]
@jozo thanks 👌
